backend:
  name: github
  repo: maartengoudsmit/rustling
  branch: decap

media_folder: '/static/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'notes'
    label: 'Notes'
    folder: '/src/lib/notes'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    identifier_field: body
    fields:
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list'}
